version: '3.7'

services:

  myFancyNodeJsApp:
    container_name: myFancyNodeJsApp
    image: salmantheexorcist/myfirstfancyapp:3.0
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "8080:3000"
    networks:
      - myspooky_isolated_network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on: 
      - myMongoDbContainer
      
  myMongoDbContainer:
    container_name: myMongoDbContainer
    image: mongo
    networks:
      - myspooky_isolated_network

networks:
  myspooky_isolated_network:
    driver: bridge 